site_name: CompoDB Documentation
docs_dir: docs

nav:
  - Home: index.md
  - CompoDB:
      - Architecture: compodb/architecture.md
      - Components: compodb/components.md
      - Procedure: compodb/procedure.md
  - Benchmark Framework:
      - Benchmarks: benchmark-demo/benchmarks.md
      - Demo UI: benchmark-demo/demoUI.md
      - Outcomes: benchmark-demo/outcomes.md
  - Quickstart: quickstart.md

plugins:
  - search
  - pdf-export