CREATE TABLE PART (
  P_PARTKEY BIGINT NOT NULL,
  P_NAME VARCHAR(55),
  P_MFGR CHAR(25),
  P_BRAND CHAR(10),
  P_TYPE VARCHAR(25),
  P_SIZE INTEGER,
  P_CONTAINER CHAR(10),
  P_RETAILPRICE DECIMAL,
  P_COMMENT VARCHAR(23)
);