import pyarrow as pa

call_center_schema_ds = pa.schema([
    ('cc_call_center_sk', pa.int64()),
    ('cc_call_center_id', pa.string()),
    ('cc_rec_start_date', pa.date32()),
    ('cc_rec_end_date', pa.date32()),
    ('cc_closed_date_sk', pa.int64()),
    ('cc_open_date_sk', pa.int64()),
    ('cc_name', pa.string()),
    ('cc_class', pa.string()),
    ('cc_employees', pa.int64()),
    ('cc_sq_ft', pa.int64()),
    ('cc_hours', pa.string()),
    ('cc_manager', pa.string()),
    ('cc_mkt_id', pa.int64()),
    ('cc_mkt_class', pa.string()),
    ('cc_mkt_desc', pa.string()),
    ('cc_market_manager', pa.string()),
    ('cc_division', pa.int64()),
    ('cc_division_name', pa.string()),
    ('cc_company', pa.int64()),
    ('cc_company_name', pa.string()),
    ('cc_street_number', pa.string()),
    ('cc_street_name', pa.string()),
    ('cc_street_type', pa.string()),
    ('cc_suite_number', pa.string()),
    ('cc_city', pa.string()),
    ('cc_county', pa.string()),
    ('cc_state', pa.string()),
    ('cc_zip', pa.string()),
    ('cc_country', pa.string()),
    ('cc_gmt_offset', pa.decimal128(15, 2)),
    ('cc_tax_percentage', pa.decimal128(15, 2))
])

catalog_page_schema_ds = pa.schema([
    ('cp_catalog_page_sk', pa.int64()),
    ('cp_catalog_page_id', pa.string()),
    ('cp_start_date_sk', pa.int64()),
    ('cp_end_date_sk', pa.int64()),
    ('cp_department', pa.string()),
    ('cp_catalog_number', pa.int64()),
    ('cp_catalog_page_number', pa.int64()),
    ('cp_description', pa.string()),
    ('cp_type', pa.string())
])


catalog_returns_schema_ds = pa.schema([
    ('cr_returned_date_sk', pa.int64()),
    ('cr_returned_time_sk', pa.int64()),
    ('cr_item_sk', pa.int64()),
    ('cr_refunded_customer_sk', pa.int64()),
    ('cr_refunded_cdemo_sk', pa.int64()),
    ('cr_refunded_hdemo_sk', pa.int64()),
    ('cr_refunded_addr_sk', pa.int64()),
    ('cr_returning_customer_sk', pa.int64()),
    ('cr_returning_cdemo_sk', pa.int64()),
    ('cr_returning_hdemo_sk', pa.int64()),
    ('cr_returning_addr_sk', pa.int64()),
    ('cr_call_center_sk', pa.int64()),
    ('cr_catalog_page_sk', pa.int64()),
    ('cr_ship_mode_sk', pa.int64()),
    ('cr_warehouse_sk', pa.int64()),
    ('cr_reason_sk', pa.int64()),
    ('cr_order_number', pa.int64()),
    ('cr_return_quantity', pa.int64()),
    ('cr_return_amount', pa.decimal128(15, 2)),
    ('cr_return_tax', pa.decimal128(15, 2)),
    ('cr_return_amt_inc_tax', pa.decimal128(15, 2)),
    ('cr_fee', pa.decimal128(15, 2)),
    ('cr_return_ship_cost', pa.decimal128(15, 2)),
    ('cr_refunded_cash', pa.decimal128(15, 2)),
    ('cr_reversed_charge', pa.decimal128(15, 2)),
    ('cr_store_credit', pa.decimal128(15, 2)),
    ('cr_net_loss', pa.decimal128(15, 2))
])

catalog_sales_schema_ds = pa.schema([
    ('cs_sold_date_sk', pa.int64()),
    ('cs_sold_time_sk', pa.int64()),
    ('cs_ship_date_sk', pa.int64()),
    ('cs_bill_customer_sk', pa.int64()),
    ('cs_bill_cdemo_sk', pa.int64()),
    ('cs_bill_hdemo_sk', pa.int64()),
    ('cs_bill_addr_sk', pa.int64()),
    ('cs_ship_customer_sk', pa.int64()),
    ('cs_ship_cdemo_sk', pa.int64()),
    ('cs_ship_hdemo_sk', pa.int64()),
    ('cs_ship_addr_sk', pa.int64()),
    ('cs_call_center_sk', pa.int64()),
    ('cs_catalog_page_sk', pa.int64()),
    ('cs_ship_mode_sk', pa.int64()),
    ('cs_warehouse_sk', pa.int64()),
    ('cs_item_sk', pa.int64()),
    ('cs_promo_sk', pa.int64()),
    ('cs_order_number', pa.int64()),
    ('cs_quantity', pa.int64()),
    ('cs_wholesale_cost', pa.decimal128(15, 2)),
    ('cs_list_price', pa.decimal128(15, 2)),
    ('cs_sales_price', pa.decimal128(15, 2)),
    ('cs_ext_discount_amt', pa.decimal128(15, 2)),
    ('cs_ext_sales_price', pa.decimal128(15, 2)),
    ('cs_ext_wholesale_cost', pa.decimal128(15, 2)),
    ('cs_ext_list_price', pa.decimal128(15, 2)),
    ('cs_ext_tax', pa.decimal128(15, 2)),
    ('cs_coupon_amt', pa.decimal128(15, 2)),
    ('cs_ext_ship_cost', pa.decimal128(15, 2)),
    ('cs_net_paid', pa.decimal128(15, 2)),
    ('cs_net_paid_inc_tax', pa.decimal128(15, 2)),
    ('cs_net_paid_inc_ship', pa.decimal128(15, 2)),
    ('cs_net_paid_inc_ship_tax', pa.decimal128(15, 2)),
    ('cs_net_profit', pa.decimal128(15, 2))
])

customer_schema_ds = pa.schema([
    ('c_customer_sk', pa.int64()),
    ('c_customer_id', pa.string()),
    ('c_current_cdemo_sk', pa.int64()),
    ('c_current_hdemo_sk', pa.int64()),
    ('c_current_addr_sk', pa.int64()),
    ('c_first_shipto_date_sk', pa.int64()),
    ('c_first_sales_date_sk', pa.int64()),
    ('c_salutation', pa.string()),
    ('c_first_name', pa.string()),
    ('c_last_name', pa.string()),
    ('c_preferred_cust_flag', pa.string()),
    ('c_birth_day', pa.int64()),
    ('c_birth_month', pa.int64()),
    ('c_birth_year', pa.int64()),
    ('c_birth_country', pa.string()),
    ('c_login', pa.string()),
    ('c_email_address', pa.string()),
    ('c_last_review_date_sk', pa.string())
])

customer_address_schema_ds = pa.schema([
    ('ca_address_sk', pa.int64()),
    ('ca_address_id', pa.string()),
    ('ca_street_number', pa.string()),
    ('ca_street_name', pa.string()),
    ('ca_street_type', pa.string()),
    ('ca_suite_number', pa.string()),
    ('ca_city', pa.string()),
    ('ca_county', pa.string()),
    ('ca_state', pa.string()),
    ('ca_zip', pa.string()),
    ('ca_country', pa.string()),
    ('ca_gmt_offset', pa.decimal128(15, 2)),
    ('ca_location_type', pa.string())
])

customer_demographics_schema_ds = pa.schema([
    ('cd_demo_sk', pa.int64()),
    ('cd_gender', pa.string()),
    ('cd_marital_status', pa.string()),
    ('cd_education_status', pa.string()),
    ('cd_purchase_estimate', pa.int64()),
    ('cd_credit_rating', pa.string()),
    ('cd_dep_count', pa.int64()),
    ('cd_dep_employed_count', pa.int64()),
    ('cd_dep_college_count', pa.int64())
])

date_dim_schema_ds = pa.schema([
    ('d_date_sk', pa.int64()),
    ('d_date_id', pa.string()),
    ('d_date', pa.date32()),
    ('d_month_seq', pa.int64()),
    ('d_week_seq', pa.int64()),
    ('d_quarter_seq', pa.int64()),
    ('d_year', pa.int64()),
    ('d_dow', pa.int64()),
    ('d_moy', pa.int64()),
    ('d_dom', pa.int64()),
    ('d_qoy', pa.int64()),
    ('d_fy_year', pa.int64()),
    ('d_fy_quarter_seq', pa.int64()),
    ('d_fy_week_seq', pa.int64()),
    ('d_day_name', pa.string()),
    ('d_quarter_name', pa.string()),
    ('d_holiday', pa.string()),
    ('d_weekend', pa.string()),
    ('d_following_holiday', pa.string()),
    ('d_first_dom', pa.int64()),
    ('d_last_dom', pa.int64()),
    ('d_same_day_ly', pa.int64()),
    ('d_same_day_lq', pa.int64()),
    ('d_current_day', pa.string()),
    ('d_current_week', pa.string()),
    ('d_current_month', pa.string()),
    ('d_current_quarter', pa.string()),
    ('d_current_year', pa.string())
])

household_demographics_schema_ds = pa.schema([
    ('hd_demo_sk', pa.int64()),
    ('hd_income_band_sk', pa.int64()),
    ('hd_buy_potential', pa.string()),
    ('hd_dep_count', pa.int64()),
    ('hd_vehicle_count', pa.int64())
])

income_band_schema_ds = pa.schema([
    ('ib_income_band_sk', pa.int64()),
    ('ib_lower_bound', pa.int64()),
    ('ib_upper_bound', pa.int64())
])

inventory_schema_ds = pa.schema([
    ('inv_date_sk', pa.int64()),
    ('inv_item_sk', pa.int64()),
    ('inv_warehouse_sk', pa.int64()),
    ('inv_quantity_on_hand', pa.int64())
])

item_schema_ds = pa.schema([
    ('i_item_sk', pa.int64()),
    ('i_item_id', pa.string()),
    ('i_rec_start_date', pa.date32()),
    ('i_rec_end_date', pa.date32()),
    ('i_item_desc', pa.string()),
    ('i_current_price', pa.decimal128(15, 2)),
    ('i_wholesale_cost', pa.decimal128(15, 2)),
    ('i_brand_id', pa.int64()),
    ('i_brand', pa.string()),
    ('i_class_id', pa.int64()),
    ('i_class', pa.string()),
    ('i_category_id', pa.int64()),
    ('i_category', pa.string()),
    ('i_manufact_id', pa.int64()),
    ('i_manufact', pa.string()),
    ('i_size', pa.string()),
    ('i_formulation', pa.string()),
    ('i_color', pa.string()),
    ('i_units', pa.string()),
    ('i_container', pa.string()),
    ('i_manager_id', pa.int64()),
    ('i_product_name', pa.string())
])

promotion_schema_ds = pa.schema([
    ('p_promo_sk', pa.int64()),
    ('p_promo_id', pa.string()),
    ('p_start_date_sk', pa.int64()),
    ('p_end_date_sk', pa.int64()),
    ('p_item_sk', pa.int64()),
    ('p_cost', pa.decimal128(15, 2)),
    ('p_response_target', pa.int64()),
    ('p_promo_name', pa.string()),
    ('p_channel_dmail', pa.string()),
    ('p_channel_email', pa.string()),
    ('p_channel_catalog', pa.string()),
    ('p_channel_tv', pa.string()),
    ('p_channel_radio', pa.string()),
    ('p_channel_press', pa.string()),
    ('p_channel_event', pa.string()),
    ('p_channel_demo', pa.string()),
    ('p_channel_details', pa.string()),
    ('p_purpose', pa.string()),
    ('p_discount_active', pa.string())
])

reason_schema_ds = pa.schema([
    ('r_reason_sk', pa.int64()),
    ('r_reason_id', pa.string()),
    ('r_reason_desc', pa.string())
])

ship_mode_schema_ds = pa.schema([
    ('sm_ship_mode_sk', pa.int64()),
    ('sm_ship_mode_id', pa.string()),
    ('sm_type', pa.string()),
    ('sm_code', pa.string()),
    ('sm_carrier', pa.string()),
    ('sm_contract', pa.string())
])

store_schema_ds = pa.schema([
    ('s_store_sk', pa.int64()),
    ('s_store_id', pa.string()),
    ('s_rec_start_date', pa.date32()),
    ('s_rec_end_date', pa.date32()),
    ('s_closed_date_sk', pa.int64()),
    ('s_store_name', pa.string()),
    ('s_number_employees', pa.int64()),
    ('s_floor_space', pa.int64()),
    ('s_hours', pa.string()),
    ('s_manager', pa.string()),
    ('s_market_id', pa.int64()),
    ('s_geography_class', pa.string()),
    ('s_market_desc', pa.string()),
    ('s_market_manager', pa.string()),
    ('s_division_id', pa.int64()),
    ('s_division_name', pa.string()),
    ('s_company_id', pa.int64()),
    ('s_company_name', pa.string()),
    ('s_street_number', pa.string()),
    ('s_street_name', pa.string()),
    ('s_street_type', pa.string()),
    ('s_suite_number', pa.string()),
    ('s_city', pa.string()),
    ('s_county', pa.string()),
    ('s_state', pa.string()),
    ('s_zip', pa.string()),
    ('s_country', pa.string()),
    ('s_gmt_offset', pa.decimal128(15, 2)),
    ('s_tax_precentage', pa.decimal128(15, 2))
])

store_returns_schema_ds = pa.schema([
    ('sr_returned_date_sk', pa.int64()),
    ('sr_return_time_sk', pa.int64()),
    ('sr_item_sk', pa.int64()),
    ('sr_customer_sk', pa.int64()),
    ('sr_cdemo_sk', pa.int64()),
    ('sr_hdemo_sk', pa.int64()),
    ('sr_addr_sk', pa.int64()),
    ('sr_store_sk', pa.int64()),
    ('sr_reason_sk', pa.int64()),
    ('sr_ticket_number', pa.int64()),
    ('sr_return_quantity', pa.int64()),
    ('sr_return_amt', pa.decimal128(15, 2)),
    ('sr_return_tax', pa.decimal128(15, 2)),
    ('sr_return_amt_inc_tax', pa.decimal128(15, 2)),
    ('sr_fee', pa.decimal128(15, 2)),
    ('sr_return_ship_cost', pa.decimal128(15, 2)),
    ('sr_refunded_cash', pa.decimal128(15, 2)),
    ('sr_reversed_charge', pa.decimal128(15, 2)),
    ('sr_store_credit', pa.decimal128(15, 2)),
    ('sr_net_loss', pa.decimal128(15, 2))
])

store_sales_schema_ds = pa.schema([
    ('ss_sold_date_sk', pa.int64()),
    ('ss_sold_time_sk', pa.int64()),
    ('ss_item_sk', pa.int64()),
    ('ss_customer_sk', pa.int64()),
    ('ss_cdemo_sk', pa.int64()),
    ('ss_hdemo_sk', pa.int64()),
    ('ss_addr_sk', pa.int64()),
    ('ss_store_sk', pa.int64()),
    ('ss_promo_sk', pa.int64()),
    ('ss_ticket_number', pa.int64()),
    ('ss_quantity', pa.int64()),
    ('ss_wholesale_cost', pa.decimal128(15, 2)),
    ('ss_list_price', pa.decimal128(15, 2)),
    ('ss_sales_price', pa.decimal128(15, 2)),
    ('ss_ext_discount_amt', pa.decimal128(15, 2)),
    ('ss_ext_sales_price', pa.decimal128(15, 2)),
    ('ss_ext_wholesale_cost', pa.decimal128(15, 2)),
    ('ss_ext_list_price', pa.decimal128(15, 2)),
    ('ss_ext_tax', pa.decimal128(15, 2)),
    ('ss_coupon_amt', pa.decimal128(15, 2)),
    ('ss_net_paid', pa.decimal128(15, 2)),
    ('ss_net_paid_inc_tax', pa.decimal128(15, 2)),
    ('ss_net_profit', pa.decimal128(15, 2))
])

time_dim_schema_ds = pa.schema([
    ('t_time_sk', pa.int64()),
    ('t_time_id', pa.string()),
    ('t_time', pa.int64()),
    ('t_hour', pa.int64()),
    ('t_minute', pa.int64()),
    ('t_second', pa.int64()),
    ('t_am_pm', pa.string()),
    ('t_shift', pa.string()),
    ('t_sub_shift', pa.string()),
    ('t_meal_time', pa.string())
])

warehouse_schema_ds = pa.schema([
    ('w_warehouse_sk', pa.int64()),
    ('w_warehouse_id', pa.string()),
    ('w_warehouse_name', pa.string()),
    ('w_warehouse_sq_ft', pa.int64()),
    ('w_street_number', pa.string()),
    ('w_street_name', pa.string()),
    ('w_street_type', pa.string()),
    ('w_suite_number', pa.string()),
    ('w_city', pa.string()),
    ('w_county', pa.string()),
    ('w_state', pa.string()),
    ('w_zip', pa.string()),
    ('w_country', pa.string()),
    ('w_gmt_offset', pa.decimal128(15, 2))
])

web_page_schema_ds = pa.schema([
    ('wp_web_page_sk', pa.int64()),
    ('wp_web_page_id', pa.string()),
    ('wp_rec_start_date', pa.date32()),
    ('wp_rec_end_date', pa.date32()),
    ('wp_creation_date_sk', pa.int64()),
    ('wp_access_date_sk', pa.int64()),
    ('wp_autogen_flag', pa.string()),
    ('wp_customer_sk', pa.int64()),
    ('wp_url', pa.string()),
    ('wp_type', pa.string()),
    ('wp_char_count', pa.int64()),
    ('wp_link_count', pa.int64()),
    ('wp_image_count', pa.int64()),
    ('wp_max_ad_count', pa.int64())
])

web_returns_schema_ds = pa.schema([
    ('wr_returned_date_sk', pa.int64()),
    ('wr_returned_time_sk', pa.int64()),
    ('wr_item_sk', pa.int64()),
    ('wr_refunded_customer_sk', pa.int64()),
    ('wr_refunded_cdemo_sk', pa.int64()),
    ('wr_refunded_hdemo_sk', pa.int64()),
    ('wr_refunded_addr_sk', pa.int64()),
    ('wr_returning_customer_sk', pa.int64()),
    ('wr_returning_cdemo_sk', pa.int64()),
    ('wr_returning_hdemo_sk', pa.int64()),
    ('wr_returning_addr_sk', pa.int64()),
    ('wr_web_page_sk', pa.int64()),
    ('wr_reason_sk', pa.int64()),
    ('wr_order_number', pa.int64()),
    ('wr_return_quantity', pa.int64()),
    ('wr_return_amt', pa.decimal128(15, 2)),
    ('wr_return_tax', pa.decimal128(15, 2)),
    ('wr_return_amt_inc_tax', pa.decimal128(15, 2)),
    ('wr_fee', pa.decimal128(15, 2)),
    ('wr_return_ship_cost', pa.decimal128(15, 2)),
    ('wr_refunded_cash', pa.decimal128(15, 2)),
    ('wr_reversed_charge', pa.decimal128(15, 2)),
    ('wr_account_credit', pa.decimal128(15, 2)),
    ('wr_net_loss', pa.decimal128(15, 2))
])

web_sales_schema_ds = pa.schema([
    ('ws_sold_date_sk', pa.int64()),
    ('ws_sold_time_sk', pa.int64()),
    ('ws_ship_date_sk', pa.int64()),
    ('ws_item_sk', pa.int64()),
    ('ws_bill_customer_sk', pa.int64()),
    ('ws_bill_cdemo_sk', pa.int64()),
    ('ws_bill_hdemo_sk', pa.int64()),
    ('ws_bill_addr_sk', pa.int64()),
    ('ws_ship_customer_sk', pa.int64()),
    ('ws_ship_cdemo_sk', pa.int64()),
    ('ws_ship_hdemo_sk', pa.int64()),
    ('ws_ship_addr_sk', pa.int64()),
    ('ws_web_page_sk', pa.int64()),
    ('ws_web_site_sk', pa.int64()),
    ('ws_ship_mode_sk', pa.int64()),
    ('ws_warehouse_sk', pa.int64()),
    ('ws_promo_sk', pa.int64()),
    ('ws_order_number', pa.int64()),
    ('ws_quantity', pa.int64()),
    ('ws_wholesale_cost', pa.decimal128(15, 2)),
    ('ws_list_price', pa.decimal128(15, 2)),
    ('ws_sales_price', pa.decimal128(15, 2)),
    ('ws_ext_discount_amt', pa.decimal128(15, 2)),
    ('ws_ext_sales_price', pa.decimal128(15, 2)),
    ('ws_ext_wholesale_cost', pa.decimal128(15, 2)),
    ('ws_ext_list_price', pa.decimal128(15, 2)),
    ('ws_ext_tax', pa.decimal128(15, 2)),
    ('ws_coupon_amt', pa.decimal128(15, 2)),
    ('ws_ext_ship_cost', pa.decimal128(15, 2)),
    ('ws_net_paid', pa.decimal128(15, 2)),
    ('ws_net_paid_inc_tax', pa.decimal128(15, 2)),
    ('ws_net_paid_inc_ship', pa.decimal128(15, 2)),
    ('ws_net_paid_inc_ship_tax', pa.decimal128(15, 2)),
    ('ws_net_profit', pa.decimal128(15, 2))
])

web_site_schema_ds = pa.schema([
    ('web_site_sk', pa.int64()),
    ('web_site_id', pa.string()),
    ('web_rec_start_date', pa.date32()),
    ('web_rec_end_date', pa.date32()),
    ('web_name', pa.string()),
    ('web_open_date_sk', pa.int64()),
    ('web_close_date_sk', pa.int64()),
    ('web_class', pa.string()),
    ('web_manager', pa.string()),
    ('web_mkt_id', pa.int64()),
    ('web_mkt_class', pa.string()),
    ('web_mkt_desc', pa.string()),
    ('web_market_manager', pa.string()),
    ('web_company_id', pa.int64()),
    ('web_company_name', pa.string()),
    ('web_street_number', pa.string()),
    ('web_street_name', pa.string()),
    ('web_street_type', pa.string()),
    ('web_suite_number', pa.string()),
    ('web_city', pa.string()),
    ('web_county', pa.string()),
    ('web_state', pa.string()),
    ('web_zip', pa.string()),
    ('web_country', pa.string()),
    ('web_gmt_offset', pa.decimal128(15, 2)),
    ('web_tax_percentage', pa.decimal128(15, 2))
])