CREATE TABLE catalog_sales
(
    cs_sold_date_sk           BIGINT,
    cs_sold_time_sk           BIGINT,
    cs_ship_date_sk           BIGINT,
    cs_bill_customer_sk       BIGINT,
    cs_bill_cdemo_sk          BIGINT,
    cs_bill_hdemo_sk          BIGINT,
    cs_bill_addr_sk           BIGINT,
    cs_ship_customer_sk       BIGINT,
    cs_ship_cdemo_sk          BIGINT,
    cs_ship_hdemo_sk          BIGINT,
    cs_ship_addr_sk           BIGINT,
    cs_call_center_sk         BIGINT,
    cs_catalog_page_sk        BIGINT,
    cs_ship_mode_sk           BIGINT,
    cs_warehouse_sk           BIGINT,
    cs_item_sk                BIGINT NOT NULL,
    cs_promo_sk               BIGINT,
    cs_order_number           BIGINT NOT NULL,
    cs_quantity               BIGINT,
    cs_wholesale_cost         DECIMAL(15, 2),
    cs_list_price             DECIMAL(15, 2),
    cs_sales_price            DECIMAL(15, 2),
    cs_ext_discount_amt       DECIMAL(15, 2),
    cs_ext_sales_price        DECIMAL(15, 2),
    cs_ext_wholesale_cost     DECIMAL(15, 2),
    cs_ext_list_price         DECIMAL(15, 2),
    cs_ext_tax                DECIMAL(15, 2),
    cs_coupon_amt             DECIMAL(15, 2),
    cs_ext_ship_cost          DECIMAL(15, 2),
    cs_net_paid               DECIMAL(15, 2),
    cs_net_paid_inc_tax       DECIMAL(15, 2),
    cs_net_paid_inc_ship      DECIMAL(15, 2),
    cs_net_paid_inc_ship_tax  DECIMAL(15, 2),
    cs_net_profit             DECIMAL(15, 2)
);