CREATE TABLE catalog_returns
(
    cr_returned_date_sk       BIGINT,
    cr_returned_time_sk       BIGINT,
    cr_item_sk                BIGINT NOT NULL,
    cr_refunded_customer_sk   BIGINT,
    cr_refunded_cdemo_sk      BIGINT,
    cr_refunded_hdemo_sk      BIGINT,
    cr_refunded_addr_sk       BIGINT,
    cr_returning_customer_sk  BIGINT,
    cr_returning_cdemo_sk     BIGINT,
    cr_returning_hdemo_sk     BIGINT,
    cr_returning_addr_sk      BIGINT,
    cr_call_center_sk         BIGINT,
    cr_catalog_page_sk        BIGINT,
    cr_ship_mode_sk           BIGINT,
    cr_warehouse_sk           BIGINT,
    cr_reason_sk              BIGINT,
    cr_order_number           BIGINT NOT NULL,
    cr_return_quantity        BIGINT,
    cr_return_amount          DECIMAL(15, 2),
    cr_return_tax             DECIMAL(15, 2),
    cr_return_amt_inc_tax     DECIMAL(15, 2),
    cr_fee                    DECIMAL(15, 2),
    cr_return_ship_cost       DECIMAL(15, 2),
    cr_refunded_cash          DECIMAL(15, 2),
    cr_reversed_charge        DECIMAL(15, 2),
    cr_store_credit           DECIMAL(15, 2),
    cr_net_loss               DECIMAL(15, 2)
);