CREATE TABLE date_dim (
    d_date_sk BIGINT NOT NULL,
    d_date_id VARCHAR NOT NULL,
    d_date DATE,
    d_month_seq BIGINT,
    d_week_seq BIGINT,
    d_quarter_seq BIGINT,
    d_year BIGINT,
    d_dow BIGINT,
    d_moy BIGINT,
    d_dom BIGINT,
    d_qoy BIGINT,
    d_fy_year BIGINT,
    d_fy_quarter_seq BIGINT,
    d_fy_week_seq BIGINT,
    d_day_name VARCHAR,
    d_quarter_name VARCHAR,
    d_holiday VARCHAR,
    d_weekend VARCHAR,
    d_following_holiday VARCHAR,
    d_first_dom BIGINT,
    d_last_dom BIGINT,
    d_same_day_ly BIGINT,
    d_same_day_lq BIGINT,
    d_current_day VARCHAR,
    d_current_week VARCHAR,
    d_current_month VARCHAR,
    d_current_quarter VARCHAR,
    d_current_year VARCHAR
);