CREATE TABLE store (
    s_store_sk BIGINT NOT NULL,
    s_store_id VARCHAR NOT NULL,
    s_rec_start_date DATE,
    s_rec_end_date DATE,
    s_closed_date_sk BIGINT,
    s_store_name VARCHAR,
    s_number_employees BIGINT,
    s_floor_space BIGINT,
    s_hours VARCHAR,
    s_manager VARCHAR,
    s_market_id BIGINT,
    s_geography_class VARCHAR,
    s_market_desc VARCHAR,
    s_market_manager VARCHAR,
    s_division_id BIGINT,
    s_division_name VARCHAR,
    s_company_id BIGINT,
    s_company_name VARCHAR,
    s_street_number VARCHAR,
    s_street_name VARCHAR,
    s_street_type VARCHAR,
    s_suite_number VARCHAR,
    s_city VARCHAR,
    s_county VARCHAR,
    s_state VARCHAR,
    s_zip VARCHAR,
    s_country VARCHAR,
    s_gmt_offset DECIMAL(15, 2),
    s_tax_precentage DECIMAL(15, 2)
);