CREATE TABLE store_sales (
    ss_sold_date_sk BIGINT,
    ss_sold_time_sk BIGINT,
    ss_item_sk BIGINT NOT NULL ,
    ss_customer_sk BIGINT,
    ss_cdemo_sk BIGINT,
    ss_hdemo_sk BIGINT,
    ss_addr_sk BIGINT,
    ss_store_sk BIGINT,
    ss_promo_sk BIGINT,
    ss_ticket_number BIGINT NOT NULL ,
    ss_quantity BIGINT,
    ss_wholesale_cost DECIMAL(15, 2),
    ss_list_price DECIMAL(15, 2),
    ss_sales_price DECIMAL(15, 2),
    ss_ext_discount_amt DECIMAL(15, 2),
    ss_ext_sales_price DECIMAL(15, 2),
    ss_ext_wholesale_cost DECIMAL(15, 2),
    ss_ext_list_price DECIMAL(15, 2),
    ss_ext_tax DECIMAL(15, 2),
    ss_coupon_amt DECIMAL(15, 2),
    ss_net_paid DECIMAL(15, 2),
    ss_net_paid_inc_tax DECIMAL(15, 2),
    ss_net_profit DECIMAL(15, 2)
);