CREATE TABLE web_site
(
    web_site_sk               BIGINT NOT NULL,
    web_site_id               VARCHAR NOT NULL,
    web_rec_start_date        DATE,
    web_rec_end_date          DATE,
    web_name                  VARCHAR,
    web_open_date_sk          BIGINT,
    web_close_date_sk         BIGINT,
    web_class                 VARCHAR,
    web_manager               VARCHAR,
    web_mkt_id                BIGINT,
    web_mkt_class             VARCHAR,
    web_mkt_desc              VARCHAR,
    web_market_manager        VARCHAR,
    web_company_id            BIGINT,
    web_company_name          VARCHAR,
    web_street_number         VARCHAR,
    web_street_name           VARCHAR,
    web_street_type           VARCHAR,
    web_suite_number          VARCHAR,
    web_city                  VARCHAR,
    web_county                VARCHAR,
    web_state                 VARCHAR,
    web_zip                   VARCHAR,
    web_country               VARCHAR,
    web_gmt_offset            DECIMAL(15, 2),
    web_tax_percentage        DECIMAL(15, 2)
);